### ISSUE TITLE
Plot group management page

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#10]
From @andrewvanbreda

> A plot group is simply a word (term) that can be attached to 1 or more plots regardless of any other Plot Groups a plot might be in.

> We did mention a Plot Group management page in our discussions, although not sure I wrote that down anywhere.
This page would all the creation of new plot groups and assign plots to the group

> Given the above, as both the NPMS and Non NPMS type forms include the ability to select a plot/location, then those forms do indirectly make use of the Plot Group capability although they don't have any explicit Plot Group related functionality directly on the data entry forms.

**Comment by sacrevert** [comment]
Note that, resourcing wise, this requirement may be outside of the current (to end March 2021) resourcing phase.

**Comment by andrewvanbreda** [comment]
Coded, awaiting configuration, and a bug fix I have done to be applied to Warehouse.

**Comment by andrewvanbreda** [comment]
This is working now
