### ISSUE TITLE
Standard Mode My Samples page throwing error

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/plantportal#101]
The Standard Mode My Samples page is throwing an error, this uses a standard indicia report.

@johnvanbreda
This is what the warehouse is showing, I think there might be a problem with the report processing as this is a general report that seems to fail without intervention again.

15:30:46 debug Constructing XMLReportReader for report /srv/sites/warehouse1.indicia.org.uk/reports/library/samples/filterable_explore_list_mapping.xml.
15:30:46 debug Cache Library initialized
15:30:46 error Missing i18n entry general_errors.There was an SQL error: ERROR: column s.geom does not exist
LINE 14: AND (st_intersects(s.geom, st_makevalid(st_geomfromtext('',9...
^ -
SELECT s.id as "sample_id",
null as date,
st_astext(s.public_geom) as "geom",
1 as "sref_precision"
FROM cache_samples_functional s
JOIN cache_samples_nonfunctional snf ON snf.id=s.id
JOIN system sys ON sys.id=1

WHERE s.training=true AND (s.website_id in (106) OR s.created_by_id=1 OR s.blocked_sharing_tasks IS NULL OR NOT s.blocked_sharing_tasks @> ARRAY['R'::character ])
AND s.website_id in (106)

AND (s.created_by_id=84948)
AND (st_intersects(s.geom, st_makevalid(st_geomfromtext('',900913))))
LIMIT 2000 for language en_GB

**Comment by johnvanbreda** [comment]
Should be fixed - can you try now please @andrewvanbreda and close if OK?

**Comment by andrewvanbreda** [comment]
@johnvanbreda 
Fixed, thank you.
