### ISSUE TITLE
Add units to dimensions fields, page "Standard Mode - add/edit plot"

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#114]
Add text "in metres" to these field headers:
![image](https://github.com/user-attachments/assets/e935f1ae-6800-4062-9b98-a39f39a17c84)

**Comment by sacrevert** [comment]
Is it possible to make this minor change? I think we can delete "if applicable" at the same time, given that it is not a mandatory field and is a bit cumbersome.

**Comment by andrewvanbreda** [comment]
@sacrevert 
Done.
Either close issue if happy, or let me know if you want "if applicable" removed from the other fields that are on that page.

**Comment by sacrevert** [comment]
@andrewvanbreda if you could that would be great. Please close then

**Comment by andrewvanbreda** [comment]
Done
