### ISSUE TITLE
App links on website

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#115]
@BirenRathod Would you be able to add an app links block to the front page of the Plant Portal website? https://plantportal.ceh.ac.uk/

Basically identical (although ideally in Plant Portal green colour, and saying "Plant Portal recording app" rather than "NPMS recording app") to this on the NPMS website:
![image](https://github.com/user-attachments/assets/bcdf5013-515c-483e-b74a-aef2e33c2903)

It's the same app store links as the NPMS; they can be found here as well: https://plantportal.ceh.ac.uk/plant-portal-app-now-available

**Comment by BirenRathod** [comment]
@sacrevert I have added the block with color background.

**Comment by sacrevert** [comment]
Perfect, many thanks Biren!
