### ISSUE TITLE
Implement Wildflower/Indicator/Inventory functionality in NPMS Mode

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/plantportal#14]
From Oli
" I suggest that, at least in the first instance, we have the taxon-list restriction that we have for the indicator form apply to both the wildflower and indicator choice on this website. This means that: (a) actually the user will have the option of choosing more species than they actually should (i.e. indicator species will be available to those recording at indicator level; and (b) the species page of the form will need to respond to which level the user chooses (i.e. the restricted indicator list will be used if the user selects wildflower or indicator, where as the restrictions that we have in place for inventory level will apply if they choose inventory (if i recall, we have a list of higher level taxon groups that the user is restricted to at inventory level on the NPMS website)."

and further note from Oli

"I suppose we do actually have the wildflower list tagged as such in the database because of the specific form on the true NPMS website. If this is the case, then can we have the available species list being reactive to all three level choices please?"

**Comment by andrewvanbreda** [comment]
Hi @sacrevert,
Currently NPMS has this situation:

Wildflower users its own custom species list

Indicator users its own custom species list

Inventory uses the UK Master List is limited by the following Taxon Groups
clubmoss
conifer
fern
horsetail
flowering plant
ginkgo
quillwort
stonewort

I think to handle the situation you are describing with 3 different species list selections, it would be best to create 3 copies of the data entry forms, otherwise the code might get messy.
I can't see re-populating the species list dynamically working very well, as we would have to get the system to reload the page anyway when selection is made.
This also is better for the future as if you decide you want to make the forms different in other ways we won't get stuck with 3 copies.

So I suppose the next question is how do we allow the use to make their selection?
I could move the drop-down onto its own page that the user would go to first, then the user is transparently redirected to the correct data entry form, this page would avoid the need for 3 links anywhere we want the user to be able to get to the data entry forms.

**Comment by sacrevert** [comment]
>I could move the drop-down onto its own page that the user would go to first, then the user is transparently redirected to the correct data entry form, this page would avoid the need for 3 links anywhere we want the user to be able to get to the data entry forms.

Sounds good to me.

**Comment by andrewvanbreda** [comment]
This has been all done for a while now and is ready to be used
