### ISSUE TITLE
Setup Standard Mode data entry/plot pages with attributes

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/plantportal#15]
From Oli
[standardPpFields_v0.docx](https://github.com/BiologicalRecordsCentre/plantportal/files/5994807/standardPpFields_v0.docx)

"Andy, here is my outline for the data entry form templates for standard mode. There is a fair bit to accommodate for the general sample page, so I wonder whether we could group these into expandable sections, the less important ones being collapsed by default. Let me know where you have questions -- would be happy to have a web meeting if anything needs discussing."

**Comment by andrewvanbreda** [comment]
@sacrevert 
Hi Oli,
There is a bit too much here for me to think about all at once I think. 
So I will just consider one element as a starting point.
Here in the "Plot level information" section is a description of several attributes, but these would go onto the Plot Maintenance/Editing page.
So this leaves the question, is the Plot Maintenance/Editing page going to vary depending on the project type also, or are these plot attributes relevant to both project types?

**Comment by sacrevert** [comment]
Hi @andrewvanbreda 
Yes, these attributes are only relevant to Standard plots, so they would be slightly different attributes to the NPMS type (and true NPMS) plots (although of course some things are in common)

**Comment by andrewvanbreda** [comment]
@sacrevert 
Um, ok will need to have a think about how to get this to work. 
Maybe one plot maintenance page which hides different attributes depending on the project type. Will let you know

**Comment by sacrevert** [comment]
Here are the NVC data. It would be good if, ultimately, there were two options, one to select the community and one to select the sub-community if required. The selection of the community would then automatically filter the subcommunities to show only those nested within the community. (Kind of like the data entry for NPMS, where the fine habitat selection box only appears once you have selected the broad habitat)

The selection boxes could just list the codes for brevity, but perhaps the full name could appear somewhere once the code has been selected (e.g. in grey beneath the selection box?)
[NVC_community_names.zip](https://github.com/BiologicalRecordsCentre/plantportal/files/6428046/NVC_community_names.zip)

**Comment by sacrevert** [comment]
And here is the other abundance scale that I mentioned (Braun-Blanquet is the name)
[BBscale.zip](https://github.com/BiologicalRecordsCentre/plantportal/files/6428102/BBscale.zip)

**Comment by sacrevert** [comment]
Also allow Presence/absence as another, simple, "abundance" scale

**Comment by andrewvanbreda** [comment]
@sacrevert 
Hi Oli,

Just looking at this, I noticed the sub-community parent "MG7" doesn't have an entry in the main communities list

**Comment by sacrevert** [comment]
Ah, well spotted. It should have I think

**Comment by andrewvanbreda** [comment]
@sacrevert 
Alas I cannot take the credit, it was just when I did a test import into the dev warehouse it complained :)

**Comment by andrewvanbreda** [comment]
AVB: Note for myself.
The NVC community data can be imported into a termlist using the code as the term, the name can be a synonym.
A second import can then be done with the sub-communities using the main community term (the code) mapped to the parent, again using the sub-community name as a synonym.

This can then be mapped on a lockup attribute with the control type set to by a hierarchical drop-down.

The main form will then need an onChange handler to detect the change to the drop-down by the user, and this then displays the full name synonym from the database.

There is a test term list not he dev warehouse, although it does have mistakes in it because it is a test.

**Comment by sacrevert** [comment]
Hi @andrewvanbreda I list some outstanding things based on my document below:

- Add "Vegetation height average" [numerical, continuous non-negative] to the Vegetation height tab. This is just another open field for the surveyor to enter an average into if they wish, it is not a system-calculated average of the other fields.
- Grazing intensity [HIGH, MEDIUM, LOW] -- note that NONE is not actually required
- Grazing animal numbers [non-negative integer] -- both grazing options should go below the current "Which animals were grazing?" question
- The only other thing is the codified list of NVC community types, this would be a hierarchical drop-down on the Habitat details tab (see above comment [here](https://github.com/BiologicalRecordsCentre/plantportal/issues/15#issuecomment-832761158) -- the new CSV file is here 
[NVC_community_names_v2.zip](https://github.com/BiologicalRecordsCentre/plantportal/files/11372021/NVC_community_names_v2.zip)

**Comment by andrewvanbreda** [comment]
Hi @sacrevert 
I imported the communities on my machine, is the kind of thing in the screenshots ok (ignore the tab name I am using as it will go on Habitats tab. Also ignore lack of space between the two drop-downs which we can fix with a style sheet).

I included the fulls names, as limiting to just the code, then displaying the full name in a separate box is quite a bit more problematic to do. Let me know if you think that is necessary.

In particular if you could confirm that the format of <code> - <name> in the labels is ok. Thanks


![Screenshot 1](https://github.com/BiologicalRecordsCentre/plantportal/assets/2463614/f9087241-d28c-4320-93e1-90fbe0af9cd5)


![Screenshot 2](https://github.com/BiologicalRecordsCentre/plantportal/assets/2463614/00298366-0edf-4253-9f71-99f84fddc5e8)


![Screenshot 3](https://github.com/BiologicalRecordsCentre/plantportal/assets/2463614/50355fd9-12e0-4587-9733-9f8dcf1fe3ac)



![Screenshot 4](https://github.com/BiologicalRecordsCentre/plantportal/assets/2463614/0d72060d-a13d-4584-ba21-00542e30cda9)

**Comment by sacrevert** [comment]
Looks good to me @andrewvanbreda 
I assume one doesnt have to select a nested type. (Some communities don't have nested types, and even where they do it may be that the user did not determine it).

**Comment by andrewvanbreda** [comment]
@sacrevert 
Yes some entries do not have a sub-community anyway.
We can have it so that the sub-community is optional even if it is present.

Be aware some subcommunities are the same as the parent.
So we can have the situation as per this screenshot

This is correct as per the supplied spreadsheet, but we could remove the sub-comminity in this situation if you wanted, then the user could just select the parent

![Screen Shot 2023-06-09 at 11 14 27](https://github.com/BiologicalRecordsCentre/plantportal/assets/2463614/9690a6e6-2d41-4875-a105-5ba64c22b2b6)

**Comment by sacrevert** [comment]
It would be clearer to remove the subcommunity in this situation if possible and not too time-consuming for you @andrewvanbreda

**Comment by andrewvanbreda** [comment]
@sacrevert 
Shouldn't be.
I will just do that by simply manually removing those particular rows from the sub-communities sheet before the import, just leaves the parent.

**Comment by andrewvanbreda** [comment]
@sacrevert 
Community now available on Habitat tab here.
https://plantportal.ceh.ac.uk/standard-mode-data-entry

Note I haven't altered CSS yet to put a gap between the two drop-downs, but the rest should be ok.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod,
Would you be able to pull the Plant Portal reports folder whenever you get a sec please.
Thanks

**Comment by BirenRathod** [comment]
@andrewvanbreda Reports have gone live now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Perfect thanks :)

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
If you get a chance, would you be able to pull the Plant Portal reports folder please, cheers.

**Comment by BirenRathod** [comment]
@andrewvanbreda That's done.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Brilliant thanks :)

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod
If you get a second, would you be able to pull the Plant Portal reports folder again please.
Thanks

**Comment by BirenRathod** [comment]
@andrewvanbreda Which report are you after? I just pulled again the report folder after John did and I don't see any changes in the plant_portal folder. The last changed was done on the 26th.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren, I just noticed you are right, the push had failed. I pushed it now. The change was in get_plots_for_plot_group_id, although I thought they had been previous changes since 26th, but may be wrong about that.
No rush.

**Comment by BirenRathod** [comment]
@andrewvanbreda that report has gone live now.

**Comment by andrewvanbreda** [comment]
Closing this, as have put live a fix that was stopping the plot populating in edit mode
(actually same problem as this in NPMS)
https://github.com/BiologicalRecordsCentre/NPMS/issues/287
