### ISSUE TITLE
Plant Portal site needs theming

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/plantportal#21]
A theme is needed for the Plant Portal site to make it presentationally acceptable for demonstration.
Does not need to be extravagant, but a Plant Portal logo and a basic but appealing presentation are desirable.

**Comment by andrewvanbreda** [comment]
Just assigning this to you Oli for whenever you want to sort out a design team for this (at your own pace).

**Comment by sacrevert** [comment]
closing as dealt with elsewhere
