### ISSUE TITLE
Hiding PP data from iRecord verifiers

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#22]
The general idea with PP is to let admins manage their own projects and ultimately they choose whether to publish to GBIF. We don't want data exposed to iRecord verifiers (projects take responsibility for their own data quality).
@andrewvanbreda mentioned that a solution to this had already been developed for PoMS: @kitenetter @DavidRoy can you advise?

**Comment by kitenetter** [comment]
Assuming that PP is set up as a separate website in the warehouse (which I think is must be), then the website agreement covers this. You can choose to share data with iRecord for reporting (which controls whether the PP data is visible in iRecord, e.g. on the Explore pages), or for verification (which controls whether the data is exposed to verifiers), or for dataflow (which controls whether it is available for export to NBN and LERCs).

So as long as you don't tick the box for verification the data won't be visible to verifiers.

**Comment by sacrevert** [comment]
Thanks @kitenetter! 
@andrewvanbreda I assume that you know where these tick boxes are in the warehouse interface?

**Comment by andrewvanbreda** [comment]
@kitenetter @sacrevert 
I can tell you it does have its own website.
I assume Martin is talking about the actual Website Agreement list in the Warehouse UI (which is not something I have even dealt with until now). 
That list does not have any website agreement entry at all for Plant Portal, so I assume therefore going by what Martin says, data won't be going into iRecord at all at the moment.

**Comment by andrewvanbreda** [comment]
This is also backed up by looking at the filter on the iRecord Explore page maps, Plant Portal is not shown there

**Comment by andrewvanbreda** [comment]
@sacrevert
Have unassigned myself from this, don't think there is anything for me to do here, so I guess you can close it if you are happy.

**Comment by DavidRoy** [comment]
The agreement has to be pro-actively setup to share with iRecord so closing this
