### ISSUE TITLE
My Samples page configuration

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/plantportal#25]
As agreed in Skype meeting with Oli a while ago "My samples (for NPMS type) should show ID, Square name, Plot name, Plot grid ref, Date, Recorder

@BirenRathod 
When you get s ec could you pull this report onto live please. Cheers

projects/plant_portal/pp_my_visits

**Comment by BirenRathod** [comment]
@andrewvanbreda That report have gone live now.

**Comment by andrewvanbreda** [comment]
@BirenRathod
Thanks for that pull (am pretty late on this) 

Have fixed a bug with this report now, can you pull this again whenever you get a chance.

Cheers
Andy

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Actually have updated another report which you may want to pull at same time (not related to this issue).
Could you pull 
projects/plant_portal/pp_locations_for_groups
Again whenever you get chance, not urgent

**Comment by BirenRathod** [comment]
@andrewvanbreda your reports gone live now.

**Comment by andrewvanbreda** [comment]
@BirenRathod Thanks Biren, will take a look.
