### ISSUE TITLE
Small changes to data entry pages

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/plantportal#27]
1. Data entry pages to have popup for confirmation
2. Redirect to list plots page after data entry
3. Change fine habitat to "Optional fine habitat" instead "<Please select>" as this box is not mandatory (also apply to NPMS)

**Comment by andrewvanbreda** [comment]
Confirmations added to Standard Mode (not live in menu yet) and all NPMS Mode sample data entry pages.
Wording same as NPMS.

**Comment by sacrevert** [comment]
@andrewvanbreda Happy for you to close this one if it is done?

**Comment by andrewvanbreda** [comment]
@sacrevert 
Don't think this one is done yet

**Comment by andrewvanbreda** [comment]
1. Confirmations fixed.
2. Pages now redirect on completion of data entry, although have done slightly differently (as when I linked back to Plots the user can't see the data they just entered.) So have linked back to My Samples then from there added new buttons to Squares List (NPMS Mode)/Plots List (Standard Mode) and also a button directly back to data entry. This can be changed if found to be undesirable.
3. Have created some new Indicia code that allows the blank "Please select" text to be customised on the child drop-down of a hierarchical select.
The habitat select on NPMS Mode now says "Please select a fine habitat...(optional)" on its child drop-down as that wording is consistent with the syle of wording on the parent drop-down.
Helptext is added below to pre-warn users of this -> "Fine habitat is optional"

@BirenRathod 
Am wanting to add this to NPMS, but there are commits in develop that are not pushed to test/live yet. Could you let me know if it is OK to push those to live?  Cheers.

**Comment by BirenRathod** [comment]
@andrewvanbreda Wait for me to sort out that first.

**Comment by BirenRathod** [comment]
@andrewvanbreda you can now go ahead to push your code. Don't forget to pull the repository before making any commits.

**Comment by andrewvanbreda** [comment]
Added to NPMS, also similar message added to Plant Portal Standard Mode Communities

**Comment by andrewvanbreda** [comment]
Correction: Removed from Standard Mode Communities as I see another closed issue indicates this field is completely optional
https://github.com/BiologicalRecordsCentre/plantportal/issues/84
