### ISSUE TITLE
Group locations importer needs to add locations_websites record

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/plantportal#28]
groups_location model importer needs to be able to understand how to add locations_websites records.

Email info
JVB 11:25 7/7/2021
JVB 17:16 8/7/2021

**Comment by andrewvanbreda** [comment]
@sacrevert 
Previously when we spoke on Skype, you asked who would fix this and under which budget.  
I said I would get back to you.
 The answer is it will have to be me under Plant Portal budget.

**Comment by andrewvanbreda** [comment]
@sacrevert 
Fix coded. 
It is Warehouse based, so not quite sure how quickly this will actually become live, it is a bit easier when it is at the website end where I can just deploy through Pantheon.

**Comment by sacrevert** [comment]
Thanks Andy. I suppose we will leave this open until we have seen it working on live?

**Comment by andrewvanbreda** [comment]
@sacrevert 
Yes I would recommend that approach with all issues, not just this one.
The original person who raises the issue should be the one who closes it once they have observed the fix working on live.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Hi Biren,

To fix this the following file needs to be pulled onto the live Warehouse from Master.

application/models/groups_location.php

I hotfixed it and it has been reviewed by John in a pull request.
He is away today, so he suggested you did the pull, but if you want to wait for him to come back to do it let me know. As I say, he did review the file and I tested it before then also.

Thanks

**Comment by BirenRathod** [comment]
@andrewvanbreda I have updated the warehouse and it has updated groups_location.php file.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren. Will take a look in a sec.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Ok I can't see the change for some reason. Would you be able to look in the file and see if it contains the postSubmit function at the bottom please.
Thanks

**Comment by BirenRathod** [comment]
@andrewvanbreda Yes, it has got. Do you want me to send a file?

**Comment by andrewvanbreda** [comment]
@BirenRathod 
No don't worry about that. It might be some caching inside the Warehouse. I will see what it is doing tomorrow then ask John.

Thanks for your help

**Comment by BirenRathod** [comment]
@andrewvanbreda  did you clear cache from warehouse? I think you can do it from warehouse1.indicia.org.uk website.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
I can't see an option for that.
Also even if I could I probably shouldn't be clearing the Warehouse cache, as an outside contractor it is probably best I don't touch anything that could affect the performance of other projects I am not working on.
Would you be able to clear it if you think that is the way to fix the issue?
I checked and it still isn't working today.

Also I noticed the front page of the Warehouse is reporting that a database upgrade is required, although am not sure if that might be because the change I made just updates the minor bug fix number in the Warehouse applications version.php file.
Again that isn't something I would touch personally.

Let know if you need me to contact John about any of this.

Thanks

**Comment by BirenRathod** [comment]
@andrewvanbreda I have cleared cache for you. Although this might not impact of seeing your data but worth to try.

Also, I updated the database upgrade.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren,
Yes this hasn't worked, even on the importer directly running in the Warehouse UI. I will have a quick think then ask john.

Thanks for trying.

**Comment by BirenRathod** [comment]
@andrewvanbreda please ask to @johnvanbreda.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Actually just got it working, I realised I was being silly. The change won't work on the basic Location importer, and that is right.
Thanks for your help.

**Comment by andrewvanbreda** [comment]
@sacrevert 
This problem is fixed and live. I will mail you and Plantlife about it.
