### ISSUE TITLE
Add/edit square accepts all sizes

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#30]
Within NPMS mode, add/edit square should only accept 1 km squares, however, it seems to accept all grid sizes
e.g. see https://plantportal.ceh.ac.uk/npms-mode-edit-square?group_id=2134&implicit=f

(Actually, it would also be good if the uploader had this restriction too)

**Comment by andrewvanbreda** [comment]
@sacrevert 
Fixed map (see emails 21/1/2022 with Sarah).
The square importer uses a standard Indicia importer, I think it would be very difficult to get it to reject imports without 1km squares.
I suggest leaving that bit, and just relying on the users' sensible use of the system (which we always have to rely on to some extent). 
(as far as the code is concerned, it doesn't care whether it is actually 1km, although I appreciate it would be a requirement for data quality)

**Comment by andrewvanbreda** [comment]
Please close if happy
