### ISSUE TITLE
info about square upload format added to webpage

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#32]
On the square importer page, can we have some text about the required format, and a downloadable CSV example? I can create these if you add some information about the format here.

**Comment by andrewvanbreda** [comment]
@sacrevert 
The format is simple. It should be a CSV file like this, so just 3 headers.

Name,Spatial Reference,Spatial Reference System
Square name 1,TQ06,OSGB
Square name 2,TQ07,OSGB

**Comment by andrewvanbreda** [comment]
Oh it does need to be in a plain text file though (not a word doc) where the file extensions is .csv instead of .txt

**Comment by sacrevert** [comment]
Thanks Andy, can you put some text then at the head of the page as follows. I will provide an example text file to be linked as a download from where I have written **here** below.
###############################################################################################

The file format expected by the square uploader is as follows:

Name,Spatial Reference,Spatial Reference System
Square name 1,TQ1061,OSGB
Square name 2,TQ1071,OSGB

This information should be contained in a plain text file (.txt). Please see **here** for an example. Remember that, if you are using NPMS methods, all squares should be 1 km grid cells.

**Comment by sacrevert** [comment]
Thanks Andy, can you put some text then at the head of the page as follows. I will provide an example text file to be linked as a download from where I have written **here** below.

The file format expected by the square uploader is as follows. This information should be contained in a plain text file (.txt). Please see **here** for an example.
Name,Spatial Reference,Spatial Reference System
Square name 1,TQ06,OSGB
Square name 2,TQ07,OSGB

**Comment by sacrevert** [comment]
Before I create the file, can you just confirm that contents of teh Spatial Reference System column for Ireland and Channel Islands. I assume it would expect the following based on uploads to the NPMS site: OSNI, UTM
Is that right @andrewvanbreda ?

**Comment by andrewvanbreda** [comment]
@sacrevert 
Site is setup the same as NPMS.
So it has "OSNI" and  "UTM 30N (WGS84)"

**Comment by sacrevert** [comment]
OK, just to check though, when i supply squares for upload to Biren for the NPMS, I have been providing them with "UTM", not "UTM 30N (WGS84)"

I appreciate that the latter is technically correct and unambiguous, but I would just like to fully confirm the exact character string for this type of 1 km square. Thanks

**Comment by andrewvanbreda** [comment]
@sacrevert 
To confirm, go to the edit square page (link below), change the spatial reference system to the UTM one, and click on the map to observe the format in the box.

https://plantportal.ceh.ac.uk/npms-mode-edit-square

It looks to be like the format is like this for example

WV6155

This will be identical to NPMS. I have setup the site to be the same, so if you find an inconsistency, that needs to be corrected by me, not in your file

If you are going to be doing a big import and it is big, it is probably best to prepare a few rows first and import those

**Comment by sacrevert** [comment]
@andrewvanbreda @NPMSSupport Example file is here:
[squareUploadExample.zip](https://github.com/BiologicalRecordsCentre/plantportal/files/7933771/squareUploadExample.zip)

Also, the text that currently reads "This information should be contained in a plain text file with the extension changed to .csv" can be expanded as follows:

**This information should be contained in a plain text file with the extension changed to .csv
The easiest way to do this is to create the file in a spreadsheet software (e.g. Excel), and then to save the file as 'CSV (Comma delimited) (*.csv)'**

 Also, the text accompanying the zipfile could make it clear that any CSV should be unzipped before upload. Or else, and many better, put the example file as an unzipped CSV in the first place, if this is possible

**Comment by andrewvanbreda** [comment]
@sacrevert
Done, please close if happy

**Comment by sacrevert** [comment]
Seen to be fine at https://plantportal.ceh.ac.uk/npms-mode-square-importer
Closing
