### ISSUE TITLE
Empty bullets on joining open project?

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#33]
When one joins an open project (i.e. request to join a project is sucessful), e.g. 
https://plantportal.ceh.ac.uk/join-project?group_id=2027
a list of newly accessible pages is displayed. At least when i saw it earlier, this had some empty bullet points in it.
(i) Can we lose these? and
(ii) can I provide some descriptive text to go above each bulleted item?

**Comment by andrewvanbreda** [comment]
![Links](https://user-images.githubusercontent.com/2463614/148809041-7a24b623-5db0-483d-9213-1bc20f7a7997.png)

@sacrevert 
I have changed it to what is in this screenshot. Let me know thoughts

**Comment by sacrevert** [comment]
Looks great to me. Happy for you to close when deployed. Many thanks!

**Comment by andrewvanbreda** [comment]
@sacrevert 
Already deployed, the screenshot is actually from live (I did that before you approved it, as it was clear that it was at least better than what was previously there).
 (noting normal users won't see the View/Edit/Delete/Revisions tabs)
