### ISSUE TITLE
Blank column headings on all projects grid

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#34]
Some columns currently have no header on the all projects grid
https://plantportal.ceh.ac.uk/all-projects  

Can we call what is currently called "Links" "Project links"

The next one (with "Edit details" "invite..." etc.) could be "Project admin"

The last one could just be called "Request membership", however, the item "manage membership" doesn't really fit here. Could this be moved to the previous "Project admin" column?

**Comment by andrewvanbreda** [comment]
@sacrevert 
I have re-arranged this.
However this does not quite match what you suggested as I think I can see a logical separation now.

What I have done is
The Links columns is same, these are the custom links we use for projects.

- The next column I have changed to include all the membership links

- Then the last column I have only put the Edit Project Details link into.

I think this is a logical separation of the links.

I have not changed the headers yet, I will do, but it is harder than it looks, so I will leave that at low priority for now (i.e. things like irish grid need doing first)
Let me if you don't like the separation I have implemented.

**Comment by andrewvanbreda** [comment]
Note that obviously normal users won't see all these links so will be less confusing

**Comment by sacrevert** [comment]
All looks good to me. I suppose you will leave this open until the headers are done. Many thanks

**Comment by andrewvanbreda** [comment]
@sacrevert Yes

**Comment by andrewvanbreda** [comment]
@sacrevert @NPMSSupport
This has been done as per the contract which is "Project options", "Membership options".

Close if happy
