### ISSUE TITLE
Edit details link on "All projects" page doesn't go anywhere

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#36]
For example, even when masquerading as the admin for this project (username = Sarah Shuttleworth), the Edit details link for project "Jelly lichen" `group_id=2134` doesn't go anywhere (Edit details link is as follows:
https://plantportal.ceh.ac.uk/create-edit-project?group_id=2134 )

**Comment by andrewvanbreda** [comment]
@sacrevert @BirenRathod
Hi Biren,
Looking at this, the Create Project page is also missing from the main menu (so new ones can't be added either)
I have checked, and the Create/Edit Project page has been deleted.
Biren: Could this be the same problem as yesterday with the permissions?
I have checked the node.js files and can tell it is node 30 that is missing.
Obviously we don't want this to be widespread across websites.

**Comment by BirenRathod** [comment]
@andrewvanbreda I checked on the website. it is not permission issue. Actually node 30 doesn't exists on the website.

**Comment by BirenRathod** [comment]
@andrewvanbreda may be you missed to create on live but it is exist on test site. here it is https://test-brc-plantportal.pantheonsite.io/node/30/edit

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Hi Biren,
It was definitely on there. It has been removed. We can see this as all the Projects couldn't of been created without it.

Could it be related to whatever caused that permission issue?, I am worried there is a problem with things vanishing from sites whether it be permissions or whole pages

**Comment by BirenRathod** [comment]
@andrewvanbreda I didn't see that problem (removing content) on other site. This is something different. somebody might have removed it by mistake.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
OK, I will reinstate it.
Thanks for your thoughts.

**Comment by BirenRathod** [comment]
Thanks @andrewvanbreda. You can search in Drupal log that node id and see if you find any deleted page info.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Yes the logs are showing it was manually deleted by someone. They may not have realised they even had rights to do that, so I will message them to let them know to be careful with admin rights.

**Comment by andrewvanbreda** [comment]
@sacrevert 
I have reinstated the page.
However the page with refer to "Groups" on it rather than called them "Projects".
This isn't quite as easy to fix as it would appear, waiting response to a question I have put t John about this

**Comment by andrewvanbreda** [comment]
Fixed references to "Group" to say "Project" (actually don't think was working previously)
