### ISSUE TITLE
Removal of test projects

### ISSUE THREAD

**Issue by NPMSSupport** [BiologicalRecordsCentre/plantportal#37]
I know we talked about this briefly and that the way PP was set up was so this didn't happen, but I really think we need to remove all the test projects (including the ones I now regret adding on there) except for those being used for testing (including my latest one NPMS+ one which I will need going forward). Otherwise users coming in will see the first page of projects as a long list of test projects. 
@andrewvanbreda @sacrevert

**Comment by andrewvanbreda** [comment]
@NPMSSupport 
Hi,
Could you look at the projects list and give me an exact list of the ones you need keeping, and the ones you want to be removed. There are 18 projects at time of writing, don't want to remove any by accident.

Thanks.

**Comment by NPMSSupport** [comment]
The ones I need to keep are.
NPMS+
Meadow Makers
Meadow Maker (wrong one) - this is just in case there is something they don't want to loose so will have to check with them.

The rest can go (except any you need of course)

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Hi Biren,
Would you be able to get me this result please, so I can check we are going to remove the right ones. 
Thanks

select title
from indicia.groups
where id in (2134,2001,2003,2008,2009,2019,2020,
2026,2027,2114,2123,2103,2033,2127);

**Comment by BirenRathod** [comment]
@andrewvanbreda I have attached the result.
[data-1642773426268.zip](https://github.com/BiologicalRecordsCentre/plantportal/files/7914156/data-1642773426268.zip)

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Could you run this first bit of SQL as a test, and if it updates 14 rows, could you run the 2nd bit of SQL that will make the change. If the first query updates anything other than 14 rows, then let me know.
Cheers

update indicia.groups
set deleted=deleted
where id in (2134,2001,2003,2008,2009,2019,2020,
2026,2027,2114,2123,2103,2033,2127);

update indicia.groups
set deleted=true,updated_by_id=1,updated_on=now()
where id in (2134,2001,2003,2008,2009,2019,2020,
2026,2027,2114,2123,2103,2033,2127);

**Comment by BirenRathod** [comment]
@andrewvanbreda Both queries updated 14 rows.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren, I can also see it has worked on the site :)

@NPMSSupport 
Please close this issue if you are happy with the result

**Comment by sacrevert** [comment]
@NPMSSupport OK to close?

**Comment by NPMSSupport** [comment]
yes
