### ISSUE TITLE
Square importer template

### ISSUE THREAD

**Issue by NPMSSupport** [BiologicalRecordsCentre/plantportal#38]
@andrewvanbreda @sacrevert 
I was hoping that I would be able to get a template for the square importer sent over so I can test this ready for training. Currently I do not know how to create the CSV file to be uploaded.

**Comment by andrewvanbreda** [comment]
@NPMSSupport 
Yes this has been raised elsewhere.
I have added a slightly altered variation of Oli's suggested instructions to the importer

https://plantportal.ceh.ac.uk/npms-mode-square-importer

There will be an example file I have not added yet.

**Comment by andrewvanbreda** [comment]
@NPMSSupport 
Please close if happy.

**Comment by NPMSSupport** [comment]
Yes thank you this is great.

**Comment by sacrevert** [comment]
This is here https://github.com/BiologicalRecordsCentre/plantportal/issues/32
