### ISSUE TITLE
Link on member number - pending approval takes to denied access page

### ISSUE THREAD

**Issue by NPMSSupport** [BiologicalRecordsCentre/plantportal#39]
When looking at all projects and there is a member pending approval, there is an option to click on the number under the column Members. When you click on it, think that will take you to the page to approve them (I imagine that would be a logical conclusion for most) it takes you to an access denied page. Would it be better to remove this link for users so that the only option is to go via membership management?
@andrewvanbreda @sacrevert

**Comment by andrewvanbreda** [comment]
@NPMSSupport 
Fixed

I have changed this so clicking either link now goes to the same membership admin page.

Previously there were 2 membership pages for some reason (well I mistake on my part), and one had the wrong permissions on it and could only be access by website administrators (when actually it should be accessible to project administrators).

Please close if happy.

**Comment by NPMSSupport** [comment]
fab, thanks! yes please close
