### ISSUE TITLE
Word Group instead of project

### ISSUE THREAD

**Issue by NPMSSupport** [BiologicalRecordsCentre/plantportal#40]
I was hoping we could just change the text in two places on the project creation page? It currently says Create Group as the final button stage at the bottom as well as 'How users will join this group'. Can we change group to project? I just think it is more consistent. @andrewvanbreda @BirenRathod Not sure who is the best for a presumable quick job like this?

**Comment by BirenRathod** [comment]
@NPMSSupport Which pages are these? is it possible to send me those links?

**Comment by andrewvanbreda** [comment]
@BirenRathod @NPMSSupport 
I will do this as I already changed the rest of the pages but missed these two

**Comment by NPMSSupport** [comment]
@andrewvanbreda great stuff thank you

**Comment by andrewvanbreda** [comment]
@NPMSSupport 
This is now fixed and live.
I also fixed the text "Fill in details of your group below" near the top.
Please close if happy.

**Comment by sacrevert** [comment]
~~Hi all, can we wait until I have commented on issues like these please. I'm not really sure this is appropriate at the level of the Plant Portal overall~~

Sorry, misread this slightly. All looks good to me

**Comment by sacrevert** [comment]
I woul

**Comment by andrewvanbreda** [comment]
@sacrevert 
yep, just to clarify just some very minor wording alteration in language file on just one page.
Make sure the word Project is present appropriately.
