### ISSUE TITLE
Square label pop-up on map

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#42]
Within a NPMS-type project, on the List squares map, the "info" option on the map does not return any information when clicking on a square. It would be good if this could return the square grid ref

**Comment by NPMSSupport** [comment]
Yes this would be awesome!

**Comment by andrewvanbreda** [comment]
@NPMSSupport @sacrevert 
List Squares and Square administration now show a box saying (with the spatial reference obviously changing)

"You have clicked on square SX7190."

This is the same as the start of the message shown to the user on the NPMS' "Squares Near Me" page.

I have also added to Tracking The Impact also where the square name is displayed as the was only few mins extra work

Please close this issue or suggest alternative wording.

**Comment by sacrevert** [comment]
@andrewvanbreda brilliant. Thanks Andy. Closing
