### ISSUE TITLE
Projects grid to add project type

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#43]
@andrewvanbreda not a priority, but it would ultimately be good to add this information to the projects grid. That is, to note in a column whether a project is NPMS-type or Standard-type. It would be good to truncate the "Plant Portal - " part that seems to be part of the term when one chose the project type on set up, although that is not super-important.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Whenever you get a sec, could you pull this report please, not urgent
projects/plant_portal/projects_list.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda This report has gone live now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren
@sacrevert 
Project type now on grids.
I have fixed the "Plant Portal" being include on creation page terms.
I am not sure you want it, but ages ago you had an unofficial requirement to include the project creation date to be included on the grids. I am not sure you still want this, but as it was super easy to do I have coded it and hidden the column, so if you say you want it you can have it, just tell me to enable it (although note you might want one of the other columns hidden if you want to save space, up to you)

**Comment by andrewvanbreda** [comment]
Hi @sacrevert 
I think this can be closed unless you wanted any further columns?
Possible previous ones suggested in meetings include
Year start
Coodinators
Organisation (although don't think we currently store this)

I guess let me know or close.

**Comment by sacrevert** [comment]
I think you can just enable/unhide the "Project creation date" column that you mention abvoe, and then close.

**Comment by andrewvanbreda** [comment]
Year of creation now unhidden.
Have applied a change which will change the column title to "Project creation date". This will appear next time someone pulls reports from the Warehouse.
