### ISSUE TITLE
Project admin notifications etc.

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#44]
From @NPMSSupport 
> When a volunteer requests to join a project and it needs approval from the project administrator, does that project admin person get a notification? Also does the volunteer get notification when they have been approved?

From @andrewvanbreda
> It should be generating notifications already (there is a module on the central Warehouse server that does this). So it is like a normal notification, with an email sent if the user has emails setup for notifications. This should already be happening. So I would just need to create a notification screen so people can actually see the notifications. This should be easy to do, and just an hour or two to setup. The exception to this would be if I found that the module wasn't creating the notifications correctly (I haven't seen the notifications by eye, so can't be sure), that would need debugging. I am also not sure of the exact details of the notifications (e.g. whether admins get notifications too). I would guess though, the existing functionality should be complete for this (I hope).

**Comment by sacrevert** [comment]
@andrewvanbreda 
just a quick q: presumably this applies to both standard and npms type projects?

**Comment by andrewvanbreda** [comment]
@sacrevert 
Yes it would

**Comment by sacrevert** [comment]
@andrewvanbreda OK, maybe we can do this now then

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
In the live Warehouse config file (application/config/config.php) would you be able to check for me if the notify_pending_groups_users module is active please.

There should be an active (i.e. not commented out) line near the bottom saying something like this.
MODPATH.'notify_pending_groups_users'.

Could you let me know if that is the case or not (although don't change the config file yet if it isn't the case).
Cheers.

**Comment by BirenRathod** [comment]
@andrewvanbreda Yes, it is active.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Ok thanks, interesting

**Comment by NPMSSupport** [comment]
Hi @andrewvanbreda I know you are working on this, just wondered if we have an update. Also with the notification can I just double check whether the project admin would get the new member's details (email address most vital) so that they can be sent their map details and resources?

**Comment by andrewvanbreda** [comment]
@NPMSSupport 
Hi,
It is on my task list but I have not been active on fixing this because of workload.

There is no official User Information Download report for Plant Portal (simply not given as a requirement). 
I will have a look at best way for you to obtain this information.

**Comment by andrewvanbreda** [comment]
@NPMSSupport 
Yes at the moment there is no Users view page like on NPMS.
We can create one.
I am not sure about putting this on the Manage Membership grid, there may be security implications why that isn't there already.
I would need to think about all these things.
For now you will need to look at the Manage Membership page, then go to the People section near the top of page and search for the person and go to their account to find email address

**Comment by sacrevert** [comment]
@NPMSSupport @andrewvanbreda 
Just to point out that, as per my earlier emails to Plantlife, the assumption (in the short term) was that project officers at organisations would manage volunteers on their projects outside of the Plant Portal system. That is, we did not envisage some sort of full volunteer management system within Plant Portal, as there is for the NPMS. It may be that we add this in the future, but I don't think we have the resources to do this currently.
Regarding supplying users' emails, we should also be cognisant of the fact that we do not currently have a privacy policy

**Comment by sacrevert** [comment]
@andrewvanbreda @NPMSSupport I think we should park these issues, as otherwise we will be in danger of trying to do everything with limited budget and completing nothing. When the current project phase is reviewed, we can evaluate them fully and seek further funding if appropriate. The model for PP was the Chilterns project, where the project officer at the organisation managed volunteer comms etc. through their own systems

**Comment by andrewvanbreda** [comment]
@sacrevert 
OK, note the view of Users I mentioned would be very quick (prop 15 mins), although whether it is useful is another matter as not on the Manager Membership screen.

**Comment by sacrevert** [comment]
@andrewvanbreda this is just for a project admin and its members, rather than a Drupal admin?

**Comment by andrewvanbreda** [comment]
@sacrevert T
hat is true, it is website admin, like NPMS, so prob not useful.
So you are right, I do not think there is anything to be done here given your current vision for the project.

**Comment by sacrevert** [comment]
@andrewvanbreda OK, then i don't think we want that (or, at least, it is not what is being asked for). I think this is best parked, and the Chilterns model promoted for the time being. I will open another issue to separate this out from this one, and mark it low priority

**Comment by NPMSSupport** [comment]
@andrewvanbreda can I just double check though that the project admin will get an email notification if someone requests to join?
Re the emails @sacrevert yes I have advised they manage their own volunteers via their own systems, however they would still need to know the contact details of the person that has joined potentially or at least a way of identifying them to match against their own system. for example if Joe Bloggs is interested in volunteering on their project and contacts them directly, they then send them the link for the PP to sign up but they create a user name like Flower Power, then in theory the project admin might not know that was the same person.

**Comment by andrewvanbreda** [comment]
@NPMSSupport 
No you won't get email. This is still under investigation above.
You will need to check the Manage Membership page intermittently to check until this situation has finished investigation.
I have quite a few high priority items at moment which come before this (in particular Drupal 9 support for NPMS)

**Comment by andrewvanbreda** [comment]
@sacrevert @NPMSSupport (same notes included in email)
Fixed problem where project administrators did not get a notification for approvals.
Actually these were already working, but my tests were not showing them for misconfiguration reasons.

Note: This  only works for notifications for when there is membership to be approved by project administration.
There is no notification if the approval is made to the recipient. To change that would be a major fix I think as it doesn't look like we currently support that as far as I can see.

I have added the "Project Notifications" option to the menu that anyone can see (as anyone can create a project).

The other thing to note is this generates a notification, but the email is only generated if the user has email notification settings setup on their own account.
Oli: This is currently controlled through iRecord, do you want me to enable this on Plant Portal? (it is controlled with a Drupal module).
Or do you want notification email control to be left in the hands of iRecord?.
(If you want it on Plant Portal, I might need to do some tests as they are Drupal settings, we need to make sure they would stay in sync between the 2 sites).

**Comment by sacrevert** [comment]
@andrewvanbreda notification choice should be PP specific, and, in the ideal scenario, not linked to iRecord choices at all

**Comment by andrewvanbreda** [comment]
@sacrevert @NPMSSupport 
As mentioned in emails this has to be a universal setting that applies to all warehouse database notifications.

John hadn't used this area in years, but I have worked out what is happening with it.

I have now set this up on Plant Portal.
If the user also has an iRecord account, the settings will stay in sync with that account page also.

The only problem is I am not sure how to position the settings on the account page (they aren't shown on the registration page, so this shouldn't be crritical). 
Also currently it shows options for lots of different settings which aren't relevant to Plant Portal as Plant Portal is not attached to the verifucation system.
I will find a way to hide those at lower priority.

**Comment by andrewvanbreda** [comment]
Hi @sacrevert 
The other day you queried if we can close this issue.

The situation is this.

The above issue essentially the question:
"Will a project manager get a notification if someone is pending to join their project".

The answer is this:
When users join a project, the project manager will get a notification.
However that notification will only generate an email if their notification settings are setup so that they receive emails for that notification type.
They can do this on their account page.
Without the setting to receive emails, they will only see the notification on website notification pages.

So the question about whether we close this issue is simply is this is clear enough? and if not what can be done to make it clearer.
Currently the account page includes "Email notification settings" although it does include things like drop-down for verifications and notification types that come from the warehouse.

Is this ok as it is, or does it require further adjusting?
In some ways it is nice to have all the drop-downs for the types of notifications in one place, although the downside is that it makes the area more complicated.
I don't think think reducing the number of drop-downs in that notification settings area would be as easy as the benefit we would get from it, I think would need to add configuration to the module that runs this code to allow for only some drop-downs to display.
The other option would be to improve instructions on the page in some way.
It is important to note, these drop-downs are not Plant Portal specific, they cover all the notifications you might get from the warehouse, including notification emails from other projects.
I definetely cannot change that, it is tied to the warehouse, not the plant portal website.

I think the first question to answer, is if I were a Project Manager, where would I even learn about this functionality existing?......if there is somewhere already and it is clear, perhaps further adjustments are not required.

**Comment by sacrevert** [comment]
Thanks @andrewvanbreda 
I think this is just something to tell users about in documentation, so I will close this issue
