### ISSUE TITLE
New record download pages and CSV download links for samples and records

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#45]
(i) csv download links on all relevant grid pages (samples, occurrences) -- I think just CSV is sufficient for now
(ii) pages of occurrences -- sounds like we need two -- one for admin covering all occurrences on the project, one for users only.

@andrewvanbreda  if you can confirm my understanding, I will create the issues. If we are not already using the term "occurrences" in too many places on the site, then I would suggest using the term records instead, it being shorter and more widely used. So, "My records" and possible "Record administration" would be the names of the pages required.

**Comment by andrewvanbreda** [comment]
@sacrevert @NPMSSupport
Hi,
I have added download option in bottom-right of samples grid.

It would be quite a bit more work to add an occurrence download option to individual projects (and especially problematic to add to existing projects).

In the interests of getting this quickly to you, and interests of budget, what I have done for now is add a general Data Download option to the Projects menu.

This will allow standard users to download their own records and admins to download all data.

Have a go at this arrangement and let me know if you are ok with this, or you want it to be changed to project specific.
Also let me know the priority of any alterations you want.

I have just thought of one problem with this in that I realised there is no way for Project Managers to download data for their own projects, as it is website admin based.
So I guess this will need changing, but I will assume this is better than nothing as a starting point.

**Comment by sacrevert** [comment]
@andrewvanbreda thanks for this. I would say that project admins being able to download all occurrences for a project is quite high priority, maybe even the highest open issue at the moment. From what you say it sounds as though the current admin download is for website admins and covers literally all data entered on the site. Let me know if I've misunderstood

**Comment by andrewvanbreda** [comment]
@sacrevert @NPMSSupport 
As mentioned above, I have a problem of how to deal with this in any kind of quick manor.
So what I have done is add a "Records" tab to the "My Samples" and "Samples Administration" pages so I don't have to re-arrange the existing project links code.
This is now live.

The Samples Administrator page is a bit messy at the moment as the grid is so long, I will see if I can find the stylesheet change that was made to the Pollinator Monitoring Scheme site that fixed this.

I think putting the samples/occurrences on one page (but separate tabs) maybe better in the long run, as it reduces the number of links next to each project.
I don't know if you wanted the names of the "My Samples" and "Samples Administration" links changed? It is a bit difficult to change the link names on existing projects though, that would require a database hack, or jQuery override.

**Comment by sacrevert** [comment]
Thanks @andrewvanbreda that all sounds great. I agree that tabs would be better in the long run. I think the current names are fine, especially if changing them would involve the extra work you note. Regarding tabs, I'll leave it up to you to decide whether to keep this issue open, or to open a new one on that topic.

**Comment by andrewvanbreda** [comment]
@sacrevert I will leave this one open until I get chance to fix the stylesheet

**Comment by andrewvanbreda** [comment]
@sacrevert @NPMSSupport
Grid overflowed scrolling now working on those grids rather than just overflowing off edge of screen.

Close if happy with download options now on site, or provide further feedback.

**Comment by sacrevert** [comment]
@NPMSSupport If you can comment on this, that would be great. Thanks

**Comment by NPMSSupport** [comment]
Yes happy with this, might have more feedback from users at some point but for now that is fine
