### ISSUE TITLE
Plot labels/names not being pulled through in data entry

### ISSUE THREAD

**Issue by NPMSSupport** [BiologicalRecordsCentre/plantportal#48]
The plot labels/names are not appearing in the drop down list when in data entry pages. This means only the spatial ref is showing, which makes it very hard to know which plot you have selected.

**Comment by andrewvanbreda** [comment]
@sacrevert to comment on priority.
I think this is probably because the plot label was specified late in the day for Plant Portal and not included as part of data entry screen

**Comment by sacrevert** [comment]
@andrewvanbreda is it possible to estimate how much effort this would be to alter?

**Comment by andrewvanbreda** [comment]
@sacrevert 
Looks very simple, only a few minutes for the actual change itself.
Just need to allow a little time to put live and test. So I guess a couple of hours max.
Note I think Tracking The Impact is running same report and would change at same time as long as you don't mind that.

**Comment by sacrevert** [comment]
OK, sounds good. Worth doing in that case. As i think with NPMS, would be good to have a colon or dash between the plot name and spatial ref when displayed in the drop-down

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Whenever you get a second, could you pull the following report on live please
projects/plant_portal/ttl_get_plots_for_square_id.xml

Cheers

**Comment by BirenRathod** [comment]
@andrewvanbreda  that report gone live now.

**Comment by andrewvanbreda** [comment]
@BirenRathod Thanks Biren

@NPMSSupport @sacrevert 
Thanks has worked, close if happy.
Oli: This task was actually exactly 1 hour on timesheet from start to finish in the end.
