### ISSUE TITLE
Can we change the wording in list of squares from 'Edit' to 'Edit square'

### ISSUE THREAD

**Issue by NPMSSupport** [BiologicalRecordsCentre/plantportal#49]
This will prevent further confusion about the functionality of the edit link and that it isn't the one for the plots

**Comment by sacrevert** [comment]
Would also be useful if this flowed to standard mode, assuming it is appropriate

**Comment by andrewvanbreda** [comment]
@sacrevert 
See changes I made for #52, as those were made with this issue also in mind
