### ISSUE TITLE
Enable expert mode in plot creation for linear plots

### ISSUE THREAD

**Issue by NPMSSupport** [BiologicalRecordsCentre/plantportal#51]
Can be funding if necessary, but the need to see the full extent of the linear plot would be hugely useful for the stakeholders.

**Comment by sacrevert** [comment]
I think this low priority; they can upload sketch maps and photos after all

**Comment by andrewvanbreda** [comment]
@sacrevert @NPMSSupport 
Expert mode now available as per the Plantlife Contract

**Comment by andrewvanbreda** [comment]
Old and fixed.
Closing
