### ISSUE TITLE
Change wording from 'Edit' on plots to 'Add/edit plot'

### ISSUE THREAD

**Issue by NPMSSupport** [BiologicalRecordsCentre/plantportal#52]
This will show people that they need to select this in order to add plots to a square without any, as it isn't obvious where to go.

**Comment by sacrevert** [comment]
@andrewvanbreda would be useful if any change for this flowed to both npms and standard modes

**Comment by andrewvanbreda** [comment]
@sacrevert @NPMSSupport 
Have made quite a few label changes but not exactly as you specified as the Edit on that page doesn't actually Add/Edit Plots, it shows the square in question.
I will worry about Standard Mode another time as that is a completely different thing.

Changes to NPMS mode
- Admins now see "Edit square" on "Squares Administration"
- Users see "View square" as they can't edit them (unless they happened to import them)
- I changed "List Plots" to be "Add/edit plots"
- The view/edit square page title changed to "NPMS Mode - Square Details" (as this page covers both edits and viewing)

See how you get on with this as these changes, as they are more involved than you are suggesting but I think are needed to keep things clear.

**Comment by sacrevert** [comment]
OK, thanks @andrewvanbreda 
In that case I will close this, as standard mode will be a different kettle of fish
