### ISSUE TITLE
Minor label changes for plot creation page

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#57]
In order to make it clearer where grid references come from:

Change "Plot south-west corner:" to "Plot south-west corner (field collected):"
and
Change "Grid reference:" to "Grid reference (centroid generated by clicking on map):"

**Comment by andrewvanbreda** [comment]
@sacrevert 
Done.
Close if happy.
Yellow box position also changed to match suggested positions for NPMS
