### ISSUE TITLE
Wording changes for NPMS Mode square importer

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/plantportal#58]
‘Maps to Attribute’ quite an ambiguous title to someone unfamiliar with mapping, possibly ‘Database Attributes’ would be clearer? Good to have consistency between the interactive panels and the text.
 
Consider rewording to make it totally clear that each column heading in the imported .csv spreadsheet must be linked to one of the three database attribute options.

**Comment by andrewvanbreda** [comment]
importer.en.php file created

**Comment by andrewvanbreda** [comment]
@BirenRathod 
I see yesterday there were commits made to Plant Portal test. Is it ok for those to go onto the live site?

**Comment by BirenRathod** [comment]
@andrewvanbreda Those commits were already pushed on live env of PlanPortal. Which other commits have you seen?

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Ok yes I see, it isn't your stuff, it is one of the Pantheon "Test/live build artifacts added by Pantheon" messages.
Don't worry about it.

**Comment by andrewvanbreda** [comment]
@sacrevert @NPMSSupport
Wording updating to match the requests made as part of the contract.
Close if happy.
