### ISSUE TITLE
Wildflower will create full set of occurrences if no occurrences have been entered

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/plantportal#62]
@sacrevert
I have just been looking at some general things for projects on my task list.
There was a bug a while ago  in Indicia where a form with a static species grid would create an occurrence for every single row.

This was patcedh on NPMS, but I notice Plant Portal is running code without this patch.

There is no support budget to do a client helpers updates and tests, but I will patch the line of code for you to prevent incorrect data upload.

This bug wasn't actually present in Indicia for long, so it is unfortunate Plant Portal is running that version of the code. As it causes 200+ occurrences to be created for a sample, problems should be easy to spot

@BirenRathod 
Could you run this query please so I can see occurrence levels on the existing samples that have been entered. Cheers

select smp.id as sample_id, count(occ.id) as occ_count
from indicia.samples smp
left join indicia.occurrences occ on occ.sample_id = smp.id and occ.deleted=false
where smp.survey_id = 650 and smp.deleted=false
GROUP BY smp.id
order by occ_count desc;

**Comment by andrewvanbreda** [comment]
Will do an iForm update, patching didn't work

**Comment by BirenRathod** [comment]
@andrewvanbreda
[data-1652875887137_18052022.zip](https://github.com/BiologicalRecordsCentre/plantportal/files/8716086/data-1652875887137_18052022.zip)

**Comment by andrewvanbreda** [comment]
Oh right, it has affected some samples then.

Ok will have to deal with those.

@BirenRathod 
There is an iForm update I can put live, but I noticed some other commits will go with it. Is it ok to put those commits live? I assume it won't bring the new theme across?

**Comment by BirenRathod** [comment]
@andrewvanbreda that is fine, please update it. 
In fact, in near future I will put iform module in upper stream, so whenever John release iform, it goes across all sites. So you only have to worry about per site changes committed. That was my original plan too but not worked out due to other priority.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Ok, we need to be careful though doing that as NPMS currently runs some custom code that needs to site in iForm.module, and I have not worked out a way to avoid this yet.
I do have a note about looking into that.

I realise what I am saying is not ideal and what you are saying is preferred way forward.

**Comment by BirenRathod** [comment]
@andrewvanbreda Don't worry at present. When ever I do I will send you and everybody whole report first of all websites. It is not going to happen anytime soon.

**Comment by andrewvanbreda** [comment]
@sacrevert 
OK of the list Biren sent, one of the samples was my own training sample, and one has since been deleted. The rest seems to be created by two users but area are marked as training samples.
So I think that means I can close this issue as those can be left I think
