### ISSUE TITLE
Delete species occurrence button not working

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#63]
Apparently within NPMS+ mode, but might be more general.

**Comment by SarahSaxifrage** [comment]
I have created another account, but you beat me to it

**Comment by andrewvanbreda** [comment]
Hi @sacrevert 
Noted: although unable to look at this right now.

**Comment by andrewvanbreda** [comment]
AVB note to myself:
Is this related to similar issue with EU PoMS recently? If so then perhaps same fix will work.

**Comment by SarahSaxifrage** [comment]
I don't know anything about the PoMS bit. But when my volunteer tried to delete an individual species entry when on the data entry page using the bin icon button, it clicked but didn't do anything

**Comment by andrewvanbreda** [comment]
@SarahSaxifrage 
I try to look at this as soon as I am able

**Comment by andrewvanbreda** [comment]
@SarahSaxifrage @sacrevert 
Fixed, but please take note of this issue which happened during deployment

https://github.com/BiologicalRecordsCentre/plantportal/issues/64

Close this issue if you are happy that the species deletion bit is fixed.

**Comment by SarahSaxifrage** [comment]
It is fixed, thank you, I will close it now.

**Comment by SarahSaxifrage** [comment]
I can't close, @sacrevert can you close it?
