### ISSUE TITLE
Theme broken after cache clearance on live

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/plantportal#64]
@BirenRathod 
I just tried to deploy a fix for https://github.com/BiologicalRecordsCentre/plantportal/issues/63

However when I cleared the cache it has messed up the theme on the live site, but test does not have this issue.

I think it must be an existing issue that didn't rear its head until caches were cleared.

Any thoughts?

It is moaning about this, but I don't have access to that file through git because it is in Gitignore and probably shouldn't be fiddled with by me.
Uncaught TypeError: can't access property "Bridge", Bootstrap.Modal is undefined
https://plantportal.ceh.ac.uk/themes/composer/bootstrap/js/drupal.bootstrap.js?re79st:239

@sacrevert 
I am unsure of what to do, I have never had anything similar happen to this before.
I have left the site out of maintenance mode because I think it is working and there is danger it will be offline for long time.
Let me know if you prefer maintenance mode.

**Comment by andrewvanbreda** [comment]
![Broken menu](https://user-images.githubusercontent.com/2463614/176257158-4b206445-5988-4fb5-bc74-48d2c24cbf63.png)

**Comment by BirenRathod** [comment]
@andrewvanbreda This has fixed now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Brilliant thanks Biren :)
