### ISSUE TITLE
Expert mode doesn't seem to be working

### ISSUE THREAD

**Issue by SarahSaxifrage** [BiologicalRecordsCentre/plantportal#66]
Hi @andrewvanbreda I'm trying to use expert mode to draw a linear plot but it isn't working and just wanting to put a tiny square in like in non expert mode.

**Comment by andrewvanbreda** [comment]
@SarahSaxifrage 
Yes, you are right I just tried it, it looks like it isn't even attempting to run the code for this. I will look to see what has happened now.

**Comment by andrewvanbreda** [comment]
@SarahSaxifrage 
I am looking at the possibility the code may have been overwritten during an update, so will retrieve it.

@BirenRathod 
Although in theory this shouldn't happened, bit concerned some Plant Portal code has been overwritten during an iForm update.
But I have two issues.
1. On the Pantheon Dashboard dev tab, the log does not go back far enough.

2. On the deploy to Live tab, the log of deployments does go back far enough, but on that tab it doesn't let me see the code differences.

Do you know how either of these things about the Pantheon Dashboard can be resolved? I just need one to work.

On the Live tab, the comment for the deployment to the live environment says

"Changes to allow expert mode to be used, just like with the main NPMS site"

and it happened 4 months ago.
As I say the Dev table is not going back so far in time.
Cheers.

**Comment by BirenRathod** [comment]
@andrewvanbreda I recon use 'git log' command instead as Pantheon dashboard is not a reliable source if you are looking to see much older log.

**Comment by BirenRathod** [comment]
@andrewvanbreda To help further on this, I ran that command from my local repsitory and I found below information of that commit.

commit 6ffa851d91a8f2738b81d22c1ad7b9a9886783d4
Author: Andrew van Breda <support@avb-it.co.uk>
Date:   Sat Mar 5 17:04:55 2022 +0000

    Changes to allow expert mode to be used, just like with the main NPMS site

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Thanks Biren.

Just checking but looks like I can get the info I want using 
git show 6ffa851d91a8f2738b81d22c1ad7b9a9886783d4

Cheers

**Comment by andrewvanbreda** [comment]
@SarahSaxifrage 
I have fixed this, but have not had time to check it fully.
It will be useful to know whether it is doing what you yourself is expecting.

**Comment by SarahSaxifrage** [comment]
seems to be working fine now thanks @andrewvanbreda
