### ISSUE TITLE
Group admin ability to delete groups

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#71]
From @andrewvanbreda 
>I don't think it would be impossible as there is a deleted flag on the database. 
I did actually query this oddity with John once, and I can't remember exactly, but his answer related to something like it was never added because groups had an expiry date. 
It shouldn't be hard to do.

**Comment by andrewvanbreda** [comment]
@sacrevert 
Fixed and live.
Also fixed problem where Edit Project Details was never displayed for administrators.
