### ISSUE TITLE
Searching projects by Type column causes SQL error

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/plantportal#74]
Searching projects by Type column causes SQL error. Affects both the My Projects & All Projects pages.

**Comment by andrewvanbreda** [comment]
Caused by typo in the code (the column datatype was incorrect)

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Could you pull the "projects/plant_portal/projects_list.xml" report whenever you get a chance, not urgent at all.
Cheers

**Comment by BirenRathod** [comment]
@andrewvanbreda  gone live now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Brilliant thanks. Checked and is working.
