### ISSUE TITLE
Add missing attributes back in to management tab

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#78]
Andy to investigate whether attributes discoverable from test/dev warehouses, otherwise Oli to look into which are missing

**Comment by andrewvanbreda** [comment]
Hi @sacrevert 
The attribute IDs are nonsense, they must of come across from another Warehouse.
However from a previous issue, there is a document that explains the data entry form, I do have this issue in my task list.

https://github.com/BiologicalRecordsCentre/plantportal/issues/15

Maybe if you could just check the document at the top is how you would like, then I can work from that.

I have changed the Management tab to be close to what you mention in that document, apart from the Wooded question is now on Habitat tab. I also haven't added the Grazing Numbers yet as that needs to be completely new attribute (not from NPMS), also not added "Grazing (ordinal) " yet as that has a different "none" option which isn't in NPMS, so needs to be a new attribute with new termlist. 
I will create those two once you confirm document is correct.

**Comment by sacrevert** [comment]
Thanks @andrewvanbreda I'll that issue now. I'll close this one, as I think it is now a duplicate
