### ISSUE TITLE
Column spacing in grids

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#79]
I think this applies to all tables in Standard, NPMS and TTI "modes".
Can we add some blank space buffers to columns so that contents don't abut and become unreadable; I have seen this in a few places, but the below is from the https://plantportal.ceh.ac.uk/ttl-my-visits page when masquerading as user TheCity -- note lack of space between ID and Square columns
![image](https://user-images.githubusercontent.com/5985134/235684920-30228195-29dc-4d3a-b8d4-9332110f62ef.png)

**Comment by andrewvanbreda** [comment]
@sacrevert 
Fixed.

Added this to the Custom CSS section found in the Appearence settings for the theme in Drupal.

th, td 
{padding: 5px;}
