### ISSUE TITLE
Add additional buffering space to NVC dropdowns in data entry form

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#82]
This applies to some other dropdowns too, e.g., to the "Plot" and "Spatial Ref. CRS" dropdowns on the Location tab of the Enter data page

**Comment by andrewvanbreda** [comment]
Added this to the Custom CSS overrides in the theme settings on Drupal. Adds bit of spacing between controls but also heightens the input controls very slightly so characters with tails don't get cut-off.
Improves whole site, not just Standard Mode.

.ctrl-wrap {
  padding-top: 10px;
  padding-bottom: 10px;
}

input {
  padding-top: 2px;
  padding-bottom: 2px;
}

**Comment by andrewvanbreda** [comment]
Correction 
The following CSS was not working (illusion caused by the problem only tail cut-off problem only occurring on some browsers)
input {
padding-top: 2px;
padding-bottom: 2px;
}

replaced with

select.form-control {
  height: 40px;
}
