### ISSUE TITLE
Spatial conversion dropdown changes plot dimensions

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#83]
_Edit:_ Actually, just noticed that this would be irrelevant if #69 was implemented although that requires extra funding. 

On the plot edit/creation page, if you change the spatial ref CRS dropdown to another system, and then back to the original, often the original dimensions are now finer scale, and not the original ones, as it has converted the centroid rather than the entire extent of the original plot.

@andrewvanbreda if this is difficult to fix, I would be happy with a warning message pop-up that asks the user whether they want to change the CRS, just to stop people accidentally changing it and not noticing the changed associated plot extent change

Flagging as "standard" mode, but may apply to NPMS+ as well.

**Comment by andrewvanbreda** [comment]
@sacrevert 
Have just tried reproducing with constant converting and clicking for about 20 minutes.
Various zoom amounts, even Irish grid test. Standard and NPMS Modes, and I didn't see this failure occur even once.
Although I do remember us discussing this in Wallingford.
The conversion code is same as iRecord etc.
Perhaps revisit when you are back., at the moment I cannot reproduce this at all, also I do not see how this could occur given the way the code works.
