### ISSUE TITLE
Minor changes to edit plot page

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#85]
1. Change "Compass direction" to "Compass direction/aspect (if applicable)"
2. Change "Plot shape" to "Plot shape (if applicable)"
3. Change "Slope (degrees)" to "Slope in degrees (if applicable)"
4. Change "Dimensions – Length:" to "Dimensions – Length (if applicable)"
5. Change "Dimensions – Width:" to "Dimensions – Width (if applicable)"
6. Change "Elevation (m):" to "Elevation in metres (if applicable)"

**Comment by andrewvanbreda** [comment]
@sacrevert 
Done.
I also added an N/A option to the shape as discussed.

**Comment by andrewvanbreda** [comment]
Close if happy
