### ISSUE TITLE
Need to consider how system deals with vague dates

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#86]
For example, can importer deal with non day-resolved data?

**Comment by sacrevert** [comment]
@andrewvanbreda Can this be closed if import is based on iRecord general importer v2 which does deal with vague dates?

**Comment by andrewvanbreda** [comment]
Yes you are correct, it does seem to.
I just tried an import using importer 2 on my own machine, and a "Summer 2024" vague date was interpreted as 
date_start=2024-06-01
date_end=2024-08-31
in the database.
