### ISSUE TITLE
Emails and notifications not appearing to send for project user membership tasks

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/plantportal#87]

**Comment by andrewvanbreda** [comment]
@sacrevert @Sam-Amy
I have tested this.

The notifications actually work when managing groups.
The reason why no notification came though when we were testing is that if you are doing things like adding users yourself, not notifications are sent to say what you have done, as system assumes you already know.
However if someone else Join Group, a notification does appear after a few minutes delay (as send by Warehouse scheduled task).
An email is also sent by the warehouse if your notification email settings allow.

![Notification](https://github.com/BiologicalRecordsCentre/plantportal/assets/2463614/16decfe5-e2b0-4ba2-9060-561b39787971)

![Screen Shot 2023-07-07 at 11 18 06](https://github.com/BiologicalRecordsCentre/plantportal/assets/2463614/f75b9c74-3d27-486f-a686-8493c9835b42)

However there is a problem and actually it affects iRecord too.
The Invite People To Join Project (recording groups) email functionality does not work because it relies on PHP's mail function to send the email, and this does not work on Pantheon hosted sites.
I have agreed with John I will change the areas of indicia that use this function to use a Drupal specific equivalent function (which does work, as NPMS uses this)

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod,

When I had a meeting with @sacrevert a couple of weeks ago, he asked me if I could check progress on this issue with you.

Just wondering if any progress has been made on the following irecord problem, as it is essentially the same problem we are getting on Plant Portal in this issue.
https://github.com/BiologicalRecordsCentre/iRecord/issues/1522

Also mentioned here
https://github.com/BiologicalRecordsCentre/iRecord/issues/1571

Cheers

**Comment by BirenRathod** [comment]
@andrewvanbreda is this still a problem or do you want me to investigate this?

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
This still needs investigating. Are you able to have a look at what might be wrong please.

Thanks
Andy

**Comment by BirenRathod** [comment]
@andrewvanbreda I have enabled & configured the mail system module now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren.
The emails are now sending on Plant Portal.
However I tried with both hotmail and work email, and in both cases the Project (recording group) invite I sent went into my junk folders.
I there anyway to stop it going in junk?
Thanks though, this is big step forward.

**Comment by BirenRathod** [comment]
@andrewvanbreda ending to junk folder depends on your inbox settings meaning you need to allow it as an approved email address.
