### ISSUE TITLE
References to groups should be projects

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/plantportal#95]
"Thank you for submitting your group to PlantPortal." (message on **project** creation)

**Comment by sacrevert** [comment]
Also text on this page should all use "project" rather than "group": https://plantportal.ceh.ac.uk/create-edit-project

**Comment by andrewvanbreda** [comment]
Hi @sacrevert 
Fixed


Although I am going to have to find an alternative fix for this.
I can see the problem.
The Indicia client_helpers includes a language file for that page, and it is overwriting the custom Plant Portal one every single time an iForm update is done.. 
I store the custom file in Indicia support files, so am able to restore it.
However we don't want to keep having this happen, so I will try to think of an alternative.

**Comment by sacrevert** [comment]
Thanks. Feel free to close this and create a new specific issue if you prefer

**Comment by andrewvanbreda** [comment]
@sacrevert 
Leave this one open for now, as am sure they are some references to group elsewhere that should be project.

**Comment by andrewvanbreda** [comment]
Hi @sacrevert
The overwriting during iForm update issue has been resolved after consulting with John on how to overcome the problem.

**Comment by andrewvanbreda** [comment]
@sacrevert 
Closing. Have changed the original message raised in this issue, plus quite a few more, including all the confirmation messages I think are generated by the Create Project.
"Remove from group" also changed to "Remove from project" on membership management.
