### ISSUE TITLE
Standard Mode Data Entry - Switch to wizard mode

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/plantportal#98]
Hi @sacrevert 

As discussed, I have switched the Standard Mode data entry page to Wizard Mode.

Would you be able to take a look sometime and let me know your thoughts.

The unsightly text issue in the progress tabs at the top that I thought might happen is occurring.

Could you let me know

1. Thoughts on its functionality.
2. Whether you prefer this mode to be left on, or switched back to tabs mode until the text can be fixed.

**Comment by andrewvanbreda** [comment]
Actually, I have just had a thought and changed it back to Tabs mode but with a Next Step button at bottom.
This doesnt have the visual issues.
Let me know if that is ok, or if it needs to be more like an NPMS step-by-step wizard.

**Comment by sacrevert** [comment]
Looks good to me
